title: The Analyst's Lab
author: Your Name
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Links
minima:
  social_links:
    - platform: github
      user_url: https://github.com/yourusername
    - platform: linkedin
      user_url: https://linkedin.com/in/yourname

  # Top navigation menu
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about"
    - title: "Projects"
      url: "/projects"
    - title: "Contact"
      url: "/contact"
